# Set LCB_BRANCH to pick what git checkout to use when spinning up the
# application. For example:
#
# $ LCB_BRANCH="feature-branch vagrant up.
#
LCB_BRANCH = ENV['LCB_BRANCH'] || 'master'

# Script that we run to bootstrap the system to run Let's Chat
LCB_SCRIPT = <<EOF
sudo apt-get update
sudo apt-get install -y python-software-properties
sudo apt-add-repository -y ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install -y mongodb build-essential nodejs git
git clone https://github.com/sdelements/lets-chat.git
cd lets-chat
git checkout #{LCB_BRANCH}
npm install
cp settings.yml.sample settings.yml
LCB_HTTP_HOST=0.0.0.0 npm start
EOF

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu14.04"
  config.vm.define "lets-chat" do |node|
        node.vm.hostname = "lets-chat"
        node.vm.network :private_network, ip: "192.168.56.12"
        node.vm.provision :shell, :inline => LCB_SCRIPT, :privileged => false
  end
  config.vm.provider "virtualbox" do |v|
        v.gui = false
        v.name = "Lets Chat"
        v.memory = 512
  end
end

